name: Url_Shortener_Server_Build_And_Unit_Test

on:
  push:
    branches: ["main", "feat/**", "fix/**"]
    paths: ["server/**", ".github/workflows/server-build-and-unit-test.yaml"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.4"
      - name: Build
        run: go build -v ./...
      - name: Test User
        run: go test -v ./internal/user/handler_test.go
      - name: Test Url
        run: go test -v ./internal/url/handler_test.go
      - name: Test OAuth
        run: go test -v ./internal/oauth/handler_test.go
