name: CI-Server-Integration-Test

on:
  pull_request:
    branches:
      - main
      - feat/**
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref != 'refs/heads/main' }}
jobs:
  server-integration-test:
    environment:
      name: Server-Integration-Test
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.SERVER_DB_URL }}
      REDIS_URL: ${{ secrets.SERVER_REDIS_URL }}
      ACCESS_TOKEN_SECRET: ${{ secrets.SERVER_ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.SERVER_REFRESH_TOKEN_SECRET }}
      COOKIE_SECURE: true
      COOKIE_SAME_SITE: none
      COOKIE_DOMAIN: ${{ vars.SERVER_COOKIE_DOMAIN }}
    defaults:
      run:
        working-directory: ./server
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: url_shortener
        options: >-
          --health-cmd "pg_isready -U postgres -d url_shortener"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s
      redis:
        image: redis:8.0-alpine
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 5s
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.4"
      - name: Query Postgres inside Container
        env:
          PGPASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          # Execute psql inside the container named 'postgres'
          docker exec -e PGPASSWORD="$PGPASSWORD" ${{ job.services.postgres.id }} psql -U postgres -d url_shortener -c "SELECT 1;"
      - name: Ping Redis
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          # Run redis-cli inside the container named 'redis'
          docker exec ${{ job.services.redis.id }} redis-cli -a "$REDIS_PASSWORD" ping
      - name: Migrate Database
        run: go run ./cmd/migrate/main.go
      - name: Test
        run: go test -v -count=1 -timeout 60s ./...
