name: Url_Shortener_Server CI

on:
  push:
    branches: ["main", "feat/**", "fix/**"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26.4"
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
